### Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
num = float(input("\nEnter the number:"))
try:
    res = num / 0
except ZeroDivisionError:
        print("Divison by zero not allowed")
    


Enter the number:7
Divison by zero not allowed


### Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.


In [2]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [3]:
for (s,v,o) in [(s,v,o) for s in subjects for v in verbs for o in objects]:
    print(f"{s} {v} {o}")

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [4]:
n = int(input("\nEnter the number"))


Enter the number5


In [13]:
import numpy as np

In [23]:
def at_vander(x, N):
    x = np.array(x)
    return np.vander(x,N)

In [28]:
x = [1,2,3,4,5]
n = int(input("\nEnter the size of column"))
res = at_vander(x,N)
print(f"\nOutput \n\n {res}")


Enter the size of column5

Output 

 [[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
